#Common Makefile configuration bits

PORT=/dev/tty.usbmodem3a21
PROGRAMMER=stk500v2
MCU=atmega2560
BAUD=115200

INCLUDES = -I/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/avr/include/avr
CFLAGS = $(INCLUDES) $(LOCAL_CFLAGS) $(LOCAL_INCLUDES) -Wall -pedantic -gstabs -std=gnu99  -DF_CPU=16000000UL -Os -mmcu=$(MCU) -fno-exceptions -ffunction-sections -fdata-sections -std=c99
CPPFLAGS = $(INCLUDES) $(LOCAL_CPPFLAGS) $(LOCAL_INCLUDES) -Wall -pedantic -gstabs -DF_CPU=16000000UL -Os -mmcu=$(MCU) -DARDUINO=100 -Wno-variadic-macros

LDFLAGS = -Wl,--gc-sections 

COMPILER_DIRECTORY=/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin
CC=$(COMPILER_DIRECTORY)/avr-gcc
CPP=$(COMPILER_DIRECTORY)/avr-g++
AR=$(COMPILER_DIRECTORY)/avr-ar
OBJCOPY=$(COMPILER_DIRECTORY)/avr-objcopy
OBJDUMP=$(COMPILER_DIRECTORY)/avr-objdump
AVRDUDE=$(COMPILER_DIRECTORY)/avrdude
AVRDUDE_CONF=$(COMPILER_DIRECTORY)/../etc/avrdude.conf

ARDUINO_LIBRARY=libarduino.a

%.o: %.c $(HEADERS)
	$(CC) -c $(CFLAGS) $< -o $@

%.o: %.cpp
	$(CPP) -c $(CPPFLAGS) $< -o $@

%.eep : %.elf
	$(OBJCOPY) -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --o-change-warnings --change-section-lma .eeprom=0 $< $@

%.hex : %.elf
	$(OBJCOPY) -O ihex -R .eeprom $< $@

dump.txt : %.elf
	$(OBJDUMP) -D $< > $@



force_look :
	true

clean:
	@echo Removing object files
	@rm -f $(OBJECTS) $(ARDUINO_LIBRARY)
	@-rm -f *.o *.elf *.eep *.hex *.dis *.lst *.map


